# Generated by Django 2.2.4 on 2019-08-11 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_auto_20190811_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='orders',
        ),
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='labs.Client'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='operator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
